# script de build automatizado da aplicacao
name: Sigachat construcao

on:
 push:
  branches:
  - "main"
jobs:
 construcao-app:
  runs-on: ubuntu-latest
  steps:
  - name: baixar codigo fonte
    uses: actions/checkout@v4
  - name: empacotar app
    uses: actions/setup-java@v4
    with:
     distribution: 'oracle'
     java-version: '21'
  - name: executando maven
    run: mvn clean install -DskipTests
  - name: login dockerhub
    run: docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASS}}
  - name: construi imagem
    run: docker build -t fernandotetu/teste .